### ISSUE TITLE
[BUG] YahooFinanceService Error: Invalid Cookie

### ISSUE THREAD

**Issue by LarsNorgaard** [ghostfolio/ghostfolio#1873]
Any idea why I'm seeing this error in the logs today?

No data seems to load from Yahoo Finance.

**Comment by dannelind** [comment]
iam getting the same errorrs
`2023-04-19T18:54:02.235035967Z [Nest] 232  - 04/19/2023, 6:54:02 PM   ERROR [YahooFinanceService] Error: Invalid Cookie
2023-04-19T18:54:02.237321742Z [Nest] 232  - 04/19/2023, 6:54:02 PM    WARN [PortfolioCalculator] Missing initial value for symbol ADAUSD at 2023-03-28
2023-04-19T18:54:02.238058676Z [Nest] 232  - 04/19/2023, 6:54:02 PM    WARN [PortfolioCalculator] Missing initial value for symbol BTCUSD at 2023-03-28
2023-04-19T18:54:02.238589294Z [Nest] 232  - 04/19/2023, 6:54:02 PM    WARN [PortfolioCalculator] Missing initial value for symbol USDTUSD at 2023-03-29`

**Comment by dannelind** [comment]
upgraded my docker isntall to latest version (1.257.0) still got the same problem
```typescript
2023-04-19T19:40:38.780997326Z [Nest] 238  - 04/19/2023, 7:40:38 PM     LOG [NestApplication] Nest application successfully started +309ms
2023-04-19T19:40:38.783563184Z [Nest] 238  - 04/19/2023, 7:40:38 PM     LOG    ________               __  ____      ___
2023-04-19T19:40:38.783964545Z [Nest] 238  - 04/19/2023, 7:40:38 PM     LOG   / ____/ /_  ____  _____/ /_/ __/___  / (_)___
2023-04-19T19:40:38.784324626Z [Nest] 238  - 04/19/2023, 7:40:38 PM     LOG  / / __/ __ \/ __ \/ ___/ __/ /_/ __ \/ / / __ \
2023-04-19T19:40:38.784642542Z [Nest] 238  - 04/19/2023, 7:40:38 PM     LOG / /_/ / / / / /_/ (__  ) /_/ __/ /_/ / / / /_/ /
2023-04-19T19:40:38.785009935Z [Nest] 238  - 04/19/2023, 7:40:38 PM     LOG \____/_/ /_/\____/____/\__/_/  \____/_/_/\____/ v1.257.0
2023-04-19T19:40:38.785404614Z [Nest] 238  - 04/19/2023, 7:40:38 PM     LOG 
2023-04-19T19:40:38.785763719Z [Nest] 238  - 04/19/2023, 7:40:38 PM     LOG Listening at http://0.0.0.0:3333
2023-04-19T19:40:38.786109969Z [Nest] 238  - 04/19/2023, 7:40:38 PM     LOG 
2023-04-19T19:41:09.123770265Z [Nest] 238  - 04/19/2023, 7:41:09 PM   ERROR [YahooFinanceService] Error: Invalid Cookie
2023-04-19T19:41:09.127099129Z [Nest] 238  - 04/19/2023, 7:41:09 PM    WARN [PortfolioCalculator] Missing historical market data for symbol ADAUSD
2023-04-19T19:41:09.127691767Z [Nest] 238  - 04/19/2023, 7:41:09 PM    WARN [PortfolioCalculator] Missing historical market data for symbol BTCUSD
2023-04-19T19:41:09.128245533Z [Nest] 238  - 04/19/2023, 7:41:09 PM    WARN [PortfolioCalculator] Missing historical market data for symbol USDTUSD
2023-04-19T19:41:09.736896728Z [Nest] 238  - 04/19/2023, 7:41:09 PM   ERROR [YahooFinanceService] Error: Invalid Cookie
```

**Comment by dtslvr** [comment]
Related to https://github.com/gadicc/node-yahoo-finance2/issues/633.

**Comment by andi-bar157** [comment]
can confirm this issue:

[Nest] 284  - 04/20/2023, 9:56:09 AM   ERROR [YahooFinanceService] Error: Invalid Cookie
[Nest] 284  - 04/20/2023, 9:56:09 AM    WARN [PortfolioCalculator] Missing initial value for symbol 0P0000UDDI.F at 2023-04-11
[Nest] 284  - 04/20/2023, 9:56:09 AM    WARN [PortfolioCalculator] Missing initial value for symbol ADAEUR at 2023-04-11
[Nest] 284  - 04/20/2023, 9:56:09 AM    WARN [PortfolioCalculator] Missing initial value for symbol IWDA.L at 2023-04-14
[Nest] 284  - 04/20/2023, 9:56:09 AM    WARN [PortfolioCalculator] Missing initial value for symbol MIOTAEUR at 2023-04-11
[Nest] 284  - 04/20/2023, 9:56:09 AM    WARN [PortfolioCalculator] Missing initial value for symbol XDWT.L at 2023-04-14
[Nest] 284  - 04/20/2023, 9:56:09 AM    WARN [PortfolioCalculator] Missing initial value for symbol XMME.L at 2023-04-14
[Nest] 284  - 04/20/2023, 9:56:09 AM   ERROR [ExchangeRateDataService] No exchange rate has been found for USDEUR

Running Ghostfolio as Docker on Unraid Version: 6.11.5

**Comment by gadicc** [comment]
Hey all, node-yahoo-finance2 author here... looking into this now!  Thanks for reporting.

**Comment by pyranha-ch** [comment]
It looks like it's working again

**Comment by gadicc** [comment]
Thanks for reporting, @pyranha-ch!  You noticed before I did, so was great to see your message, and I'm now confirming the same.  Unclear what direction Yahoo is going with this so we'll have to watch out for it in the future, but at least a lot of the code to deal with it is already done now if we need it again :pray:

**Comment by MRobi1** [comment]
@gadicc Seeing the same errors this morning.
```
[Nest] 252  - 05/05/2023, 2:12:52 PM   ERROR [YahooFinanceService] Error: Invalid Cookie
[Nest] 252  - 05/05/2023, 2:12:54 PM   ERROR [CoinGeckoService] StatusError: Too Many Requests
[Nest] 252  - 05/05/2023, 2:12:54 PM   ERROR [YahooFinanceService] Error: Invalid Cookie
[Nest] 252  - 05/05/2023, 2:12:54 PM   ERROR [CoinGeckoService] StatusError: Too Many Requests
[Nest] 252  - 05/05/2023, 2:12:54 PM   ERROR [YahooFinanceService] Error: Invalid Cookie
[Nest] 252  - 05/05/2023, 2:13:55 PM   ERROR [YahooFinanceService] Error: Invalid Cookie
[Nest] 252  - 05/05/2023, 2:13:55 PM   ERROR [YahooFinanceService] Error: Invalid Cookie
[Nest] 252  - 05/05/2023, 2:13:58 PM   ERROR [YahooFinanceService] Error: Invalid Cookie
```

**Comment by JPFrancoia** [comment]
Looks like it's kinda fixed with release 1.266.0, but I don't think the data is getting refreshed:

```
[Nest] 146  - 05/06/2023, 10:04:11 AM   ERROR [YahooFinanceService] Error: Invalid Cookie
[Nest] 146  - 05/06/2023, 10:04:11 AM    WARN [YahooFinanceService] Fallback to yahooFinance.quoteSummary()
[Nest] 146  - 05/06/2023, 10:04:11 AM   ERROR [YahooFinanceService] Error: Invalid Cookie
[Nest] 146  - 05/06/2023, 10:04:11 AM    WARN [YahooFinanceService] Fallback to yahooFinance.quoteSummary()
[Nest] 146  - 05/06/2023, 10:04:26 AM   ERROR [YahooFinanceService] Error: Invalid Cookie
[Nest] 146  - 05/06/2023, 10:04:26 AM    WARN [YahooFinanceService] Fallback to yahooFinance.quoteSummary()
[Nest] 146  - 05/06/2023, 10:04:27 AM   ERROR [YahooFinanceService] Error: Invalid Cookie
[Nest] 146  - 05/06/2023, 10:04:27 AM    WARN [YahooFinanceService] Fallback to yahooFinance.quoteSummary()
[Nest] 146  - 05/06/2023, 10:04:53 AM   ERROR [DataGatheringService] Failed to enhance data for symbol VUSA.L by TRACKINSIGHT
[Nest] 146  - 05/06/2023, 10:04:53 AM   ERROR [DataGatheringService] StatusError: Forbidden
[Nest] 146  - 05/06/2023, 10:04:53 AM     LOG [DataGatheringService] Asset profile data gathering has been completed for VUSA.L (YAHOO).
[Nest] 146  - 05/06/2023, 10:05:13 AM   ERROR [DataGatheringService] Failed to enhance data for symbol VUSA.L by TRACKINSIGHT
[Nest] 146  - 05/06/2023, 10:05:13 AM   ERROR [DataGatheringService] StatusError: Forbidden
[Nest] 146  - 05/06/2023, 10:05:13 AM     LOG [DataGatheringService] Asset profile data gathering has been completed for VUSA.L (YAHOO).
[Nest] 146  - 05/06/2023, 10:06:29 AM   ERROR [DataGatheringService] Failed to enhance data for symbol VUSA.L by TRACKINSIGHT
[Nest] 146  - 05/06/2023, 10:06:29 AM   ERROR [DataGatheringService] StatusError: Forbidden
[Nest] 146  - 05/06/2023, 10:06:29 AM     LOG [DataGatheringService] Asset profile data gathering has been completed for VUSA.L (YAHOO).
```

I'm not getting the latest data I think

**Comment by dtslvr** [comment]
@MRobi1 Ghostfolio [1.266.0](https://github.com/ghostfolio/ghostfolio/releases/tag/1.266.0) includes a fallback to fetch quotes one by one.

However, searching for symbols is still not possible.

**Comment by thomasWos** [comment]
> @MRobi1 Ghostfolio [1.266.0](https://github.com/ghostfolio/ghostfolio/releases/tag/1.266.0) includes a fallback to fetch quotes one by one.
> 
> However, searching for symbols is still not possible.

I have the same issue. Impossible to add activities from Yahoo Finance

**Comment by dtslvr** [comment]
> However, searching for symbols is still not possible.

Search should be fixed with Ghostfolio [1.268.0](https://github.com/ghostfolio/ghostfolio/releases/tag/1.268.0).

**Comment by dtslvr** [comment]
> Hey all, node-yahoo-finance2 author here... looking into this now! Thanks for reporting.

Support @gadicc's work by hitting the ⭐ here: https://github.com/gadicc/node-yahoo-finance2
