### ISSUE TITLE
[BUG] Incorrect First Activity Date when using en-GB date format

### ISSUE THREAD

**Issue by winklevos** [ghostfolio/ghostfolio#2829]
**Important Notice**

The issue tracker is **ONLY** used for reporting bugs. New features should be discussed in our [Slack](https://join.slack.com/t/ghostfolio/shared_invite/zt-vsaan64h-F_I0fEo5M0P88lP9ibCxFg) community or in [Discussions](https://github.com/ghostfolio/ghostfolio/discussions).

Incomplete or non-reproducible issues may be closed, but we are here to help! If you encounter difficulties reproducing the bug or need assistance, please reach out to our community channels mentioned above.

Thank you for your understanding and cooperation!

**Bug Description**

Holding First Activity date shows the day before the earliest activity when using `en-GB`

**To Reproduce**

1. Set user Locale to `en-GB`
2. Create activity for anything on `01/01/2024`
3. View the holding overview
4. See `First Activity` is date -1

**Expected behavior**

First Activity should match the first activity under the holding.

**Screenshots**

![image](https://github.com/ghostfolio/ghostfolio/assets/30995408/b34c8a89-e493-4522-91e6-5835c59f79a5)

**Logs**

**Environment**

- Ghostfolio Version 2.34.0
- Self-hosted
- Experimental Features **disabled**
- Browser `Firefox 121.0` and  `Edge 120.0.2210.91` 
- OS `Windows 11`

**Additional context**

Looks that some areas aren't considering the activity date is stored in UTC, `"date": "2023-12-31T14:00:00.000Z",`

**Comment by karter16** [comment]
ahhhh is this what causes this issue. I've been trying to hunt this down for ages. will experiment.

**Comment by karter16** [comment]
Looks like this has been fixed in 2.51

**Comment by will76** [comment]
Same bug here using pt locale

**Comment by Citrus0299** [comment]
This is still an issue to this day. 
It also depends on the timezone and locale info provided by the browser which can be changed using dev tools.
This also affects ghostfol.io. I tested Europe/Berlin and Europe/London. Lodon is currently equal to UTC so it's correct there, but one day behind for Europe/Berlin
