### ISSUE TITLE
Securities listed on the London Stock Exchange incorrectly valued

### ISSUE THREAD

**Issue by vmajor** [ghostfolio/ghostfolio#300]
Securities listed at  the LSE are priced in pence, but ghostfolio interprets the value as pounds. This leads to some extraordinarily profitable trades in my portfolio (+12000%)

**Comment by dtslvr** [comment]
Hello @vmajor 

Thank you for creating this issue. Can you please export a sample transaction and add the content of the file `ghostfolio-export-2021XXXXXXXX.json` to this issue? That would help a lot to reproduce and analyse the problem.

Thank you 🙂

**Comment by vmajor** [comment]
How do I export a sample transaction? On a quick scan I cannot find such an option. Nevertheless the problem can be explained here for example:

+139’022.01 USD
Change

+12’240.04%
Performance

**32.82
GBP Ø Buy Price

4’050.00
GBP Market Price**

If I enter the buy price in p (pence) to match the LSE data feed that you are using, ghostfolio assumes this is in GBP and blows out my asset value while performance looks sane. If I convert p to GBP (to match ghostfolio), my asset value is correct, but my performance statistic is otherworldly.

**Comment by dtslvr** [comment]
> How do I export a sample transaction? On a quick scan I cannot find such an option.

You can export your transactions here:

<img width="1192" alt="export-transactions" src="https://user-images.githubusercontent.com/4159106/129889344-0e462643-f04f-4f1b-b400-ae1322c9f0de.png">

> Nevertheless the problem can be explained here for example:
> 
> +139’022.01 USD
> Change
> 
> +12’240.04%
> Performance
> 
> **32.82
> GBP Ø Buy Price
> 
> 4’050.00
> GBP Market Price**

What symbol is this?

**Comment by vmajor** [comment]
Found it:
```
{
  "meta": {
    "date": "2021-08-18T12:33:12.600Z",
    "version": "dev"
  },
  "orders": [
    {
 "currency": "GBP",
      "dataSource": "YAHOO",
      "date": "2020-11-24T23:00:00.000Z",
      "fee": 0,
      "quantity": 25,
      "symbol": "AVV.L",
      "type": "BUY",
      "unitPrice": 32.82
    }
  ]
}
```

**Comment by dtslvr** [comment]
> Found it

Thanks a lot for the export. That really helps to analyse this issue.

I think I have found the problem coming from an inconsistency in the _Yahoo Finance_ service ([current data vs. historic data](https://money.stackexchange.com/questions/58913/yahoo-finance-data-inconsistencies-between-historic-and-current-data)). There is a check now for `GBp` to convert it to `GBP` if needed. Does it make sense for you?

**Comment by vmajor** [comment]
Great and sure. How do I apply the fix to my installation?

**Comment by dtslvr** [comment]
> Great and sure. How do I apply the fix to my installation?

I have merged the fix, please checkout the latest changes from the `main` branch.

**Comment by vmajor** [comment]
OK. That did not work for me. I checked out  main, reinstalled everything (yarn install), and I still have the same error/old version.

**Comment by dtslvr** [comment]
> OK. That did not work for me. I checked out main, reinstalled everything (yarn install), and I still have the same error/old version.

Hm, `yarn install` has no effect, because no dependencies have changed.

1. Have you restarted your server?
2. Are you able to set a break point in _Visual Studio Code_ ([apps/api/src/services/data-provider/yahoo-finance/yahoo-finance.service.ts Line 78](https://github.com/ghostfolio/ghostfolio/pull/301/files#diff-7be88e7782ecbd969f1651da9ab3b2fc9ec36a2963784030dc2cbcec79cae690R78)) to check if the new code is executed?
3. Have you migrated the unit price of your transaction? It should be `40.53` (`GBP`) instead of `4053` (`GBp`)

**Comment by vmajor** [comment]
I can confirm that this is now fixed.

I had to in fact run an install as the client was referencing modules that no longer existed/were different in some way, and the database schema changed too.

**Comment by dtslvr** [comment]
Thanks for the feedback @vmajor. Great to hear it is working correctly now 🙂

**Comment by Abzie** [comment]
Hi,

There seems to be a regression on this issue, somewhere in the code GBp transactions are now being treated as GBP again.

When I imported my portfolio, RKT.L and SEMB.L symbols are affected.

Otherwise, thank you for the amazing software!

**Comment by Abzie** [comment]
v1.185.0 has resolved this again.

Thanks @dtslvr

**Comment by dtslvr** [comment]
> v1.185.0 has resolved this again.

Okay great, but I'm not so sure that anything has changed at all lately 😃
