### ISSUE TITLE
Yahoo Finance: Failed to get crumb error ("Too Many Requests")

### ISSUE THREAD

**Issue by alfwro13** [ghostfolio/ghostfolio#6118]
**Bug Description**

```
[Nest] 332  - 12/31/2025, 9:21:32 AM   ERROR [YahooFinanceService] Error: Failed to get crumb, status 429, statusText: Too Many Requests
    at _getCrumb (/ghostfolio/apps/api/node_modules/yahoo-finance2/script/src/lib/getCrumb.js:273:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async _getCrumb (/ghostfolio/apps/api/node_modules/yahoo-finance2/script/src/lib/getCrumb.js:181:24)
    at async YahooFinance.yahooFinanceFetch [as _fetch] (/ghostfolio/apps/api/node_modules/yahoo-finance2/script/src/lib/yahooFinanceFetch.js:65:23)
    at async YahooFinance.moduleExec [as _moduleExec] (/ghostfolio/apps/api/node_modules/yahoo-finance2/script/src/lib/moduleExec.js:121:18)
    at async YahooFinance.quote (/ghostfolio/apps/api/node_modules/yahoo-finance2/script/src/modules/quote.js:132:21)
    at async YahooFinanceService.getQuotes (/ghostfolio/apps/api/main.js:1:507577)
[Nest] 332  - 12/31/2025, 9:21:32 AM    WARN [YahooFinanceService] Fallback to yahooFinance.quoteSummary()
    at async Promise.all (index 0)
    at async DataProviderService.getQuotes (/ghostfolio/apps/api/main.js:1:29575)
    at async ExchangeRateDataService.loadCurrencies (/ghostfolio/apps/api/main.js:1:17368)

[Nest] 333  - 12/31/2025, 9:15:38 AM   ERROR [YahooFinanceService] HTTPError: Too Many Requests
    at YahooFinance.yahooFinanceFetch [as _fetch] (/ghostfolio/apps/api/node_modules/yahoo-finance2/script/src/lib/yahooFinanceFetch.js:134:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async YahooFinance.moduleExec [as _moduleExec] (/ghostfolio/apps/api/node_modules/yahoo-finance2/script/src/lib/moduleExec.js:121:18)
    at async YahooFinance.quote (/ghostfolio/apps/api/node_modules/yahoo-finance2/script/src/modules/quote.js:132:21)
    at async YahooFinanceService.getQuotes (/ghostfolio/apps/api/main.js:1:507577)
    at async Promise.all (index 0)
    at async DataProviderService.getQuotes (/ghostfolio/apps/api/main.js:1:29575)
    at async CurrentRateService.getValues (/ghostfolio/apps/api/main.js:1:674420)
    at async RoaiPortfolioCalculator.computeSnapshot (/ghostfolio/apps/api/main.js:1:680034)
    at async PortfolioSnapshotProcessor.calculatePortfolioSnapshot (/ghostfolio/apps/api/main.js:1:713894) {
  code: 429
}
```

**To Reproduce**

1. Start Ghostfolio

**Expected Behavior**

Ghostfolio should fetch data from yahoo finance 

**Screenshots**

<img width="1059" height="204" alt="Image" src="https://github.com/user-attachments/assets/e0cd6b9d-94c4-4443-a838-9c79d564f9e3" />

**Logs**

**Environment**

- Ghostfolio Version 2.224.2
- Self-hosted
- Experimental Features disabled
- Browsers: Chromium
- OS: Linux

**Additional Context**

**Comment by dtslvr** [comment]
Related issue: https://github.com/gadicc/yahoo-finance2/issues/977

**Comment by dojoca** [comment]
Having the same issue here... glad I am not the only one. Hopefully it's just a glitch on Yahoo's side.

**Comment by alfwro13** [comment]
This is most likely yet another attempt by yahoo to kill the unofficial API. My guess is that it will take some time before (if at all) it is working again :(

**Comment by dojoca** [comment]
> This is most likely yet another attempt by yahoo to kill the unofficial API. My guess is that it will take some time before (if at all) it is working again :(

Thats my suspicion too. Everything must be as enshittified as possible.

**Comment by alfwro13** [comment]
Looks like the upstream yahoo-finance2 has been fixed. Can that be pushed to this repo?
Thanks and Happy New Year everyone.

**Comment by pilamb** [comment]
same issue

**Comment by thiagonovais** [comment]
> same issue

It is already solved in the latest release.

**Comment by pilamb** [comment]
> > same issue
> 
> It is already solved in the latest release.

Yes, I just updated the code and works fine. Thanks!

**Comment by 9Marin** [comment]
Hello, i use the docker.io/ghostfolio/ghostfolio:latest image, i still get the issue on my side. Is any specific action needed to fix it ?

**Comment by aschils** [comment]
Same issue here with ghostfolio/ghostfolio:latest, even after deploying the latest image today. Thanks.

**Comment by thiagonovais** [comment]
I updated to 2.232.0 release a few days ago and I'm not experiencing any issues to this regard
